permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Convex Lenses"
id : "84028387907"
description : "A quick demonstration of convex lenses"
thumb: "thumb.gif"
version: "0.0.2"

ml_url: "//minutelabs.io"
ml_library: "//labs.minutelabs.io/library"
ml_assets: "//labs.minutelabs.io/assets"
library_path: "library-build"

show :
  branding: true
  details: true
  comments: true
