permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Convex Lenses" # changeme
id : "" # changeme
description : "A quick demonstration of convex lenses" # changeme
thumb: "http://minutelabs.io/assets/THUMB_IMAGE" # changem
version: "0.0.1"

ml_url: "http://minutelabs.io"
ml_library: "http://labs.minutelabs.io/library"
ml_assets: "http://labs.minutelabs.io/assets"
library_path: "library" # changeme

show :
  branding: true
  details: true
  comments: true
